// <auto-generated />
using System;
using EFCoreTestRespository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreTestDemo.Migrations
{
    [DbContext(typeof(MyTestDbContext))]
    [Migration("20201108084351_UpdateNameAndType")]
    partial class UpdateNameAndType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreTestModel.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("ID")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAddr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnName("USER_NAME")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserPwd")
                        .IsRequired()
                        .HasColumnName("USER_PWD")
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("SYS_USER");

                    b.HasComment("用户表");
                });
#pragma warning restore 612, 618
        }
    }
}
